name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "Data Flow"
        replace: "DataFlow"
